version: '3.9'
services:
  api:
    build: ./api
    restart: always
    tty: true
    ports:
      - '3000:3000'
    working_dir: /workspace
    volumes:
      - ./api:/workspace
      - /workspace/node_modules
    command: npm run start:dev
    depends_on:
      - db
  db:
    image: mysql:8.0
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nest_todo
      MYSQL_PASSWORD: root
  client:
    build: ./public
    restart: always
    tty: true
    ports:
      - '4000:3000'
    working_dir: /workspace
    volumes:
      - ./public:/workspace
      - /workspace/node_modules
    command: npm run dev
volumes:
  db_data:
